name: Spawn-OG
description: A Minecraft Plugin simplifies teleporting to the spawn location.
description: A drop-in replacement for EssentialsSpawn
version: '${version}'
api-version: '${apiVersion}'
authors: [ kasumabalidps, NotAlexNoyle ]
website: https://github.com/true-og/Spawn-OG
main: spawnog.SpawnOG
api-version: 1.19
commands:
  spawn:
    description: Teleport yourself (or another player) to the server spawn
    usage: /spawn [player]
    permission: spawnog.teleport
  setspawn:
    description: Set or clear the server spawn point
    usage: /setspawn [normalize-view] [normalize-position] | /setspawn unset
    permission: spawnog.admin
permissions:
  spawnog.teleport:
    description: Use /spawn on yourself
    default: true
  spawn.others:
    description: Use /spawn <player>
    default: op
  spawnog.admin:
    description: Use /setspawn
    default: op
